server:
  port: 8085

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka       TODO Sin Load Balance
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost        TODO Sin Load Balancer
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categoria/**
        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/producto/**
        - id: ms-compra-service
          uri: lb://ms-compra-service
          predicates:
            - Path=/compra/**