#spring.application.name=ms-config-serve
server:
  port: 7070




spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Uhziel-1/SV.2025-1.git
          searchPaths: config-data
          default-label: main
  security:
    user:
      name: root
      password: 123456